apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: c4p7ss7fd-java-quarkus
  janus-idp.io/tekton: c4p7ss7fd-java-quarkus
  backstage.io/kubernetes-id: c4p7ss7fd-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: c4p7ss7fd-java-quarkus
resources:
- deployment.yaml
- route.yaml
- service.yaml
